### PR TITLE
updated gr-bruninga recipe

### PR DESCRIPTION
**Pull request by VladislavF**
added new depends, branch, and changed url to bkerler's repo

### CODE REVIEW

**Comment by willcode** [comment]
We should get an OK from the original author and the new author before changing sources.

**Comment by VladislavF** [comment]
Sure, but the current recipe will not build with gnuradio >=3.8
Bjorn's repo actually builds for 3.10 and I've also pushed a functionality bugfix to it. Basically the original hadn't been updated in 6 years at least iirc.

**Comment by VladislavF** [comment]
Understandable, how can we get Bjorn's input on this (I can't seem to @ him)? I assumed he hadn't merged because the original author is unresponsive/unavailable.

**Comment by VladislavF** [comment]
@bkerler and @tkuester thoughts?

**Comment by tkuester** [comment]
Hey! While I'd love to maintain this, the reality is that I've been pulled
in multiple other directions. If someone else is willing to maintain it
though, I'd be happy to let them take the reins!

**Comment by bkerler** [comment]
For me, there is no reason to maintain it if the original author is still available. I'm happy to help porting to new versions but the main intention is that the original author of the modules maintain it.

**Comment by VladislavF** [comment]
> For me, there is no reason to maintain it if the original author is still available. I'm happy to help porting to new versions but the main intention is that the original author of the modules maintain it.

Would you like to instead open a PR into the original repo then? I have actually submitted a PR to you as well. If we can merge that into yours and then yours into @tkuester 's repo, then I could modify this PR to just update the depends and branch (if needed), leaving the original URL.

**Comment by willcode** [comment]
@bkerler has already put in a PR. This is why we need someone who wants to be known as the maintainer. Otherwise, the code will be up to date for exactly one commit.

**Comment by VladislavF** [comment]
I didn't realize there was one open already. if Tim wants to merge that, it would be optimal I think.

**Comment by argilo** [comment]
@VladislavF: Since @tkuester would like to hand off the project and you seem to have some interest in it, would you like to become the maintainer? If so, we could continue development in your fork and point the recipe at it.

**Comment by VladislavF** [comment]
> @VladislavF: Since @tkuester would like to hand off the project and you seem to have some interest in it, would you like to become the maintainer? If so, we could continue development in your fork and point the recipe at it.

If nobody is willing to merge the changes, then so be it. I'd rather do that, than have a broken recipe. Pybombs recipes should point to working code to increase trust and usability.

**Review by argilo — APPROVED** [review]
Thanks for stepping up to maintain this, @VladislavF! I had a look over your fork, and it's in good shape so I think it makes sense to point the recipe to it.

**Comment by VladislavF** [comment]
I have updated the recipe to point at my fork for LTS since nobody else is willing to hold responsibility. There are now branches for maint-3.10 and maint-3.7 in case anyone wants to build on older versions as GR is updated in the future. I will do my best to keep master up-to-date with the current release.

**Review by willcode — APPROVED** [review]

**Comment by tkuester** [comment]
Thank you all for taking care of this old module! I trust it is in good
hands!

**Pull request merged**
