### PR TITLE
added new gr-lora implementation

### PR DESCRIPTION
**Pull request by martynvdijke**
Added my repo which contains new and improved gr-lora sdr implementation

### CODE REVIEW

**Comment by argilo** [comment]
Sorry for the delay in looking at this.

This recipe doesn't currently work because the filename is incorrect. It should have a `.lwr` extension.

**Comment by martynvdijke** [comment]
Hi,

Whoops, must have missed that somehow.
I fixed the extension in the new commit.

**Comment by willcode** [comment]
@martynvdijke Now the PR includes both files (.lwr and not).

Since https://github.com/martynvdijke/gr-lora_sdr is a fork of https://github.com/tapparelj/gr-lora_sdr, which is still active, have you considered contributing to the original repo and adding that one to pybombs?

**Comment by willcode** [comment]
Added tappareli version, since that version was active somewhat recently. The martynvdijke version has a bunch of more recent updates. If they are not going to be merged back into tappareli, then maybe your project can get renamed (or at least the recipe can be) to avoid confusion with the original. So, closing for the moment. Feel free to submit the recipe again under a distinct name. Could be gr-lora_sdr2. We do have a number of LoRa recipes, and I don't really know which ones are in use.

**Pull request closed without merging**
