### PR TITLE
Removed all the wget, as on gr-recipes

### PR DESCRIPTION
**Pull request by marcusmueller**
See https://github.com/gnuradio/gr-recipes/pull/16

### CODE REVIEW

**Comment by ckuethe** [comment]
Merged, thanks!

**Comment by mbr0wn** [comment]
Why though? The wget was correct, or did it cause issues?

**Comment by ckuethe** [comment]
Aesthetics. I never liked typing "wget+". 

Also, it's incorrect to say that "wget" was the fetcher if it was being fetched by requests.

**Comment by mbr0wn** [comment]
No, the fetcher is called 'wget', but it doesn't execute wget. If you remove the wget, you're relying on PyBOMBSes internal auto-discovery of the right fetcher. I would not recommend that for the official recipes. This is more of a feature for those people typing in URLs on the command line and whatnot.

The fetcher is still called 'wget'. See: https://github.com/gnuradio/pybombs/blob/master/pybombs/fetchers/wget.py

`wget+` is thus correct.

**Comment by marcusmueller** [comment]
Point being that the fetcher definition by `wget+` is as exact as the
fetcher identification by regex; the explicit declaration always has
priority, so nothing bad can happen here, imho.
I really like keeping `wget+` for backwards compatibility, but a URL
starting with `http:` should be fetched by exactly that fetcher.

**Comment by mbr0wn** [comment]
Actually, there's git resources that start with `http://`. The regex for wget checks that it's a .tar.gz or something like that.

...which is another good reason to keep the wget.

**Comment by marcusmueller** [comment]
Well, I see your point, but for git, which is a multi-protocol fetcher,
the `git+` syntax is obviously required.

Shit, I hadn't noticed that part of the regex; that will break quite a
few fetchers. Waah! Can you reset master to the commit before mine?

**Comment by mbr0wn** [comment]
No, it's public, but you can submit another PR.

**Comment by marcusmueller** [comment]
https://github.com/gnuradio/gr-recipes/pull/17

**Comment by ckuethe** [comment]
Applied the revert PRs


On Fri, Apr 8, 2016 at 3:13 PM, Marcus Müller <notifications@github.com>
wrote:

> https://github.com/gnuradio/gr-recipes/pull/17
>
>
> On 09.04.2016 00:07, mbr0wn wrote:
> >
> > No, it's public, but you can submit another PR.
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/gnuradio/gr-etcetera/pull/4#issuecomment-207625418>
> >
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/gnuradio/gr-etcetera/pull/4#issuecomment-207627392>
>



-- 
GDB has a 'break' feature; why doesn't it have 'fix' too?

**Pull request merged**
